var div00 = document.getElementById("div00");
var div01 = document.getElementById("div01");
var div02 = document.getElementById("div02");
var div03 = document.getElementById("div03");
var div04 = document.getElementById("div04");
var div05 = document.getElementById("div05");
var div06 = document.getElementById("div06");
var div07 = document.getElementById("div07");
var div08 = document.getElementById("div08");
var div09 = document.getElementById("div09");
var div10 = document.getElementById("div10");
var div11 = document.getElementById("div11");
var div12 = document.getElementById("div12");
var div13 = document.getElementById("div13");
var name = window.prompt("Enter your name: ");
alert("Your name is " + name);
